### ISSUE TITLE
Authentication Failure

### ISSUE THREAD

**Issue by viable-hartman** [jeslopcru/VarnishAdmin#3]
$varnish = new VarnishAdmin\VarnishAdminSocket('varnish', 6082, '4.1.9');
$varnish->setSecret('a8421f62-f0a1-4556-a80e-f3bd2a014078');
$varnish->connect(300);

This throws a "Uncaught Exception: Authentication failed" and has a code 500 returned.

Is this not the way to authenticate?

**Comment by viable-hartman** [comment]
After some debugging I discovered that Varnish 4.1.9 requires a NEW_LINE after the secret even if the /etc/varnish/secret file does not have a NEW_LINE.  I made the fix in this pull request: [https://github.com/jeslopcru/VarnishAdmin/pull/5](https://github.com/jeslopcru/VarnishAdmin/pull/5)

I also added the backendList command.

**Comment by jeslopcru** [comment]
Fix with #5
